os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "8.12.0"
jdk:
    - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle
env:
    global:
        - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
        - JHI_DISABLE_WEBPACK_LOGS=true
before_install:
    - java -version
    - sudo /etc/init.d/mysql stop
    - sudo /etc/init.d/postgresql stop
    # Use this for Protractor
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install -g yo
install:
    - npm install
    - npm link
    - npm run lint
    - npm test
script:
    - git clone https://github.com/jhipster/jhipster-sample-app.git
    - cd jhipster-sample-app
    - npm install
    - npm link generator-jhipster-primeng-charts
    - yo jhipster-primeng-charts --default --force
    - npm lint
    - npm run webpack:build
    - ./mvnw &
    - sleep 60
    - npm run e2e
