os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "6.11.0"
jdk:
    - oraclejdk8
cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle
        - $HOME/.yarn-cache
env:
    global:
        - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
before_install:
    - java -version
    - sudo /etc/init.d/mysql stop
    - sudo /etc/init.d/postgresql stop
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install -g npm
    - npm install -g yarn
    - yarn global add yo
install:
    - yarn install
    - yarn link
    - gulp eslint
    - gulp test
script:
    - git clone https://github.com/jhipster/jhipster-sample-app-ng2.git
    - cd jhipster-sample-app-ng2
    - yarn install
    - yarn link generator-jhipster-primeng-charts
    - yo jhipster-primeng-charts --default --force
    - yarn run webpack:build
    - ./mvnw &
    - sleep 40
    - yarn e2e
