os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "8.11.1"
jdk:
    - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle
env:
    global:
        - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
before_install:
    - java -version
    - sudo /etc/init.d/mysql stop
    - sudo /etc/init.d/postgresql stop
    # Use this for Protractor
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # Install Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn -v
    - yarn global add yo
install:
    - yarn install
    - yarn link
    - yarn lint
    - yarn test
script:
    - git clone https://github.com/jhipster/jhipster-sample-app.git
    - cd jhipster-sample-app
    - yarn install
    - yarn link generator-jhipster-primeng-charts
    - yo jhipster-primeng-charts --default --force
    - yarn lint
    - yarn run webpack:build
    - ./mvnw &
    - sleep 60
    - yarn e2e
